"""added profile pic

Revision ID: 477a6f944f8c
Revises: 76ecf950caa8
Create Date: 2025-03-01 20:41:46.967002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477a6f944f8c'
down_revision = '76ecf950caa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
