"""Add is_folder to IndexedFile

Revision ID: 4ebac0ddd174
Revises: df4cdfaca5c9
Create Date: 2025-03-11 02:38:43.868985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ebac0ddd174'
down_revision = 'df4cdfaca5c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indexed_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_folder', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indexed_file', schema=None) as batch_op:
        batch_op.drop_column('is_folder')

    # ### end Alembic commands ###
