"""added filetype

Revision ID: 62da3e7a65d6
Revises: d369a18481f5
Create Date: 2025-04-01 02:27:17.649978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62da3e7a65d6'
down_revision = 'd369a18481f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indexed_file', schema=None) as batch_op:
        batch_op.alter_column('filetype',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indexed_file', schema=None) as batch_op:
        batch_op.alter_column('filetype',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
