"""added filetype

Revision ID: 76998b9b71d8
Revises: c325eb902fa2
Create Date: 2025-04-01 02:15:48.131068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76998b9b71d8'
down_revision = 'c325eb902fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indexed_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filetype', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indexed_file', schema=None) as batch_op:
        batch_op.drop_column('filetype')

    # ### end Alembic commands ###
