"""Added refresh_token to CloudStorageAccount

Revision ID: 882ca3c96ede
Revises: 5e8d47f066ee
Create Date: 2025-03-25 01:51:34.093419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882ca3c96ede'
down_revision = '5e8d47f066ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloud_storage_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloud_storage_account', schema=None) as batch_op:
        batch_op.drop_column('refresh_token')

    # ### end Alembic commands ###
