"""added cloud storage model

Revision ID: a66e4db2cae1
Revises: e80047309c87
Create Date: 2025-03-24 03:06:18.742788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66e4db2cae1'
down_revision = 'e80047309c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloud_storage_account', schema=None) as batch_op:
        batch_op.alter_column('access_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cloud_storage_account', schema=None) as batch_op:
        batch_op.alter_column('access_token',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
