"""made changes

Revision ID: c881575d8751
Revises: 67e3dee8cb70
Create Date: 2025-03-31 14:37:39.992183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c881575d8751'
down_revision = '67e3dee8cb70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indexed_file', schema=None) as batch_op:
        batch_op.drop_constraint('indexed_file_filepath_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indexed_file', schema=None) as batch_op:
        batch_op.create_unique_constraint('indexed_file_filepath_key', ['filepath'])

    # ### end Alembic commands ###
