"""added gmail

Revision ID: d87a4b408b78
Revises: 62da3e7a65d6
Create Date: 2025-04-05 18:21:28.145715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87a4b408b78'
down_revision = '62da3e7a65d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indexed_file', schema=None) as batch_op:
        batch_op.alter_column('cloud_file_id',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=1024),
               existing_nullable=True)
        batch_op.alter_column('mime_type',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indexed_file', schema=None) as batch_op:
        batch_op.alter_column('mime_type',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('cloud_file_id',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
